name: Nodejs
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/5de2d7f2-fae3-458f-80ff-864cfa0aa09b
templateName: nodejs
description: It features non-blocking I/O and high processing performance through the use of JavaScript, along with a single-threaded event loop.
group:
  - JavaScript
